In [20]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
import sklearn



In [2]:
# import the data set
df=pd.read_csv("iot23_combined.csv")

In [5]:
# splitting the data into X,y
X=df.iloc[:,1:-1].values
y=df.iloc[:,-1].values
print(X,y)

[[1.0000e+00 1.8357e+04 0.0000e+00 ... 1.8000e+02 0.0000e+00 0.0000e+00]
 [1.0000e+00 0.0000e+00 0.0000e+00 ... 6.0000e+01 0.0000e+00 0.0000e+00]
 [1.0000e+00 0.0000e+00 0.0000e+00 ... 6.0000e+01 0.0000e+00 0.0000e+00]
 ...
 [1.0000e+00 0.0000e+00 0.0000e+00 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [1.0000e+00 0.0000e+00 0.0000e+00 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [1.0000e+00 0.0000e+00 0.0000e+00 ... 0.0000e+00 0.0000e+00 0.0000e+00]] ['PartOfAHorizontalPortScan' 'PartOfAHorizontalPortScan'
 'PartOfAHorizontalPortScan' ... 'DDoS' 'DDoS' 'DDoS']


In [6]:
labelencoder=LabelEncoder()

y=labelencoder.fit_transform(y)


In [9]:
#splitting the data :    
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [11]:
# perform feature scailing using Standerd scaler 
st= StandardScaler()
st.fit_transform(X_train)
st.fit(X_test)

StandardScaler()

In [14]:

# Create Random Forest Classifier
random_forest = RandomForestClassifier(n_estimators = 1000)
random_forest.fit(X_train, y_train)     
y_predRF = random_forest.predict(X_test)
accuracy_Random_forest=accuracy_score(y_test, y_predRF)
print("accuracy of Random Forest Algorithm=",accuracy_Random_forest*100)

accuracy of Random Forest Algorithm= 72.92369669722675


In [15]:
#Create Decision Tree Classifier 
decision_tree = DecisionTreeClassifier()
decision_tree.fit(X_train, y_train)
y_predDT = decision_tree.predict(X_test)
accuracy_Decision_Tree = accuracy_score(y_test, y_predDT)
print("accuracy of Decision Tree Algorithm=",accuracy_Decision_Tree*100)

accuracy of Decision Tree Algorithm= 72.93027247965833


In [16]:
# K-Nearest Neighbour Algorithm (KNN)
KNN= KNeighborsClassifier(n_neighbors=10)
KNN.fit(X_train, y_train)
y_predKNN= KNN.predict(X_test)
accuarcy_KNN=accuracy_score(y_test,y_predKNN)
print("accuracy of K-Nearest Nighbour=",accuarcy_KNN*100)

accuracy of K-Nearest Nighbour= 72.95622951557249


In [17]:
#Gaussian Naive Bayes Algorithm 
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_predgnb = gnb.predict(X_test)
accuarcy_gnb=accuracy_score(y_test,y_predgnb)
print("accuracy of Suppor Gaussian Naive Bayes=",accuarcy_gnb*100)


accuracy of Suppor Gaussian Naive Bayes= 26.035253115709544


In [24]:
#classification Report
from sklearn.metrics import classification_report

In [30]:
target_names = ['class 0', 'class 1', 'class 2',"class3","class4","class5","class6",
                "class7","class8","class9","class10","class11"]
print(classification_report(y_test, y_predRF, target_names=target_names))

C:\Users\9902013491.UPS\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

     class 0       0.99      1.00      0.99       766
     class 1       0.96      0.55      0.70     39780
     class 2       0.61      0.14      0.23      3049
      class3       0.56      0.83      0.67         6
      class4       0.78      0.38      0.51        74
      class5       1.00      1.00      1.00         3
      class6       0.00      0.00      0.00         1
      class7       1.00      0.20      0.33         5
      class8       1.00      0.82      0.90     27741
      class9       1.00      0.60      0.75         5
     class10       0.68      0.00      0.00     52533
     class11       0.68      1.00      0.81    164976

    accuracy                           0.73    288939
   macro avg       0.77      0.54      0.57    288939
weighted avg       0.75      0.73      0.65    288939



C:\Users\9902013491.UPS\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\9902013491.UPS\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [31]:
target_names = ['class 0', 'class 1', 'class 2',"class3","class4","class5","class6",
                "class7","class8","class9","class10","class11"]
print(classification_report(y_test, y_predDT, target_names=target_names))

C:\Users\9902013491.UPS\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\9902013491.UPS\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

     class 0       0.99      1.00      1.00       766
     class 1       0.96      0.55      0.70     39780
     class 2       0.64      0.14      0.23      3049
      class3       0.56      0.83      0.67         6
      class4       0.78      0.38      0.51        74
      class5       1.00      1.00      1.00         3
      class6       0.00      0.00      0.00         1
      class7       0.00      0.00      0.00         5
      class8       1.00      0.82      0.90     27741
      class9       1.00      0.60      0.75         5
     class10       0.65      0.00      0.00     52533
     class11       0.68      1.00      0.81    164976

    accuracy                           0.73    288939
   macro avg       0.69      0.53      0.55    288939
weighted avg       0.75      0.73      0.65    288939



C:\Users\9902013491.UPS\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [32]:
target_names = ['class 0', 'class 1', 'class 2',"class3","class4","class5","class6",
                "class7","class8","class9","class10","class11"]
print(classification_report(y_test, y_predKNN, target_names=target_names))

C:\Users\9902013491.UPS\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\9902013491.UPS\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

     class 0       0.97      0.98      0.98       766
     class 1       0.95      0.55      0.70     39780
     class 2       0.85      0.11      0.19      3049
      class3       0.42      0.83      0.56         6
      class4       0.81      0.39      0.53        74
      class5       0.50      0.33      0.40         3
      class6       0.00      0.00      0.00         1
      class7       0.00      0.00      0.00         5
      class8       1.00      0.82      0.90     27741
      class9       1.00      0.60      0.75         5
     class10       0.67      0.00      0.00     52533
     class11       0.68      1.00      0.81    164976

    accuracy                           0.73    288939
   macro avg       0.65      0.47      0.48    288939
weighted avg       0.75      0.73      0.65    288939



C:\Users\9902013491.UPS\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [41]:

print(classification_report(y_test, y_predgnb))

C:\Users\9902013491.UPS\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\9902013491.UPS\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.79      0.96      0.87       766
           2       0.50      0.00      0.00     39780
           3       0.49      0.11      0.18      3049
           4       0.42      0.83      0.56         6
           5       0.00      0.00      0.00        74
           6       0.60      1.00      0.75         3
           7       0.00      0.00      0.00         1
           8       0.50      0.20      0.29         5
           9       0.44      0.00      0.00     27741
          10       1.00      0.40      0.57         5
          11       0.23      0.90      0.37     52533
          12       0.98      0.16      0.28    164976

    accuracy                           0.26    288939
   macro avg       0.46      0.35      0.30    288939
weighted avg       0.72      0.26      0.23    288939



C:\Users\9902013491.UPS\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\9902013491.UPS\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\9902013491.UPS\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\9902013491.UPS\Anaconda3\li